src/Entity/Championship.php
<?php

namespace App\Entity;

use App\Repository\ChampionshipRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ChampionshipRepository::class)]
class Championship
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_start = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_end = null;

    #[ORM\OneToMany(mappedBy: "championship", targetEntity: Tournament::class)]
    private Collection $tournaments;

    #[ORM\ManyToOne(inversedBy: "championships")]
    private ?User $admin = null;

    #[ORM\Column]
    private bool $public = false;

    public function __construct()
    {
        $this->tournaments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getDateStart(): ?\DateTimeInterface
    {
        return $this->date_start;
    }

    public function setDateStart(\DateTimeInterface $date_start): static
    {
        $this->date_start = $date_start;

        return $this;
    }

    public function getDateEnd(): ?\DateTimeInterface
    {
        return $this->date_end;
    }

    public function setDateEnd(\DateTimeInterface $date_end): static
    {
        $this->date_end = $date_end;

        return $this;
    }

    /**
     * @return Collection<int, Tournament>
     */
    public function getTournaments(): Collection
    {
        return $this->tournaments;
    }

    public function addTournament(Tournament $tournament): static
    {
        if (!$this->tournaments->contains($tournament)) {
            $this->tournaments->add($tournament);
            $tournament->setChampionship($this);
        }

        return $this;
    }

    public function removeTournament(Tournament $tournament): static
    {
        if ($this->tournaments->removeElement($tournament)) {
            // set the owning side to null (unless already changed)
            if ($tournament->getChampionship() === $this) {
                $tournament->setChampionship(null);
            }
        }

        return $this;
    }

    public function __toString(): string
    {
        return $this->getName();
    }

    public function getPercentDone(): float
    {
        $startDate = $this->getDateStart();
        $endDate = $this->getDateEnd();
        $now = new \DateTime();
        $total = $endDate->diff($startDate)->days;
        $elapsed = $now->diff($startDate)->days;
        return round(($elapsed / $total) * 100);
    }

    public function getAdmin(): ?User
    {
        return $this->admin;
    }

    public function setAdmin(?User $admin): static
    {
        $this->admin = $admin;

        return $this;
    }

    public function isPublic(): bool
    {
        return $this->public;
    }

    public function setPublic(bool $public): static
    {
        $this->public = $public;

        return $this;
    }
}

src/Form/ChampionshipType.php
<?php

namespace App\Form;

use App\Entity\Championship;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ChampionshipType extends AbstractType
{
    public function buildForm(
        FormBuilderInterface $builder,
        array $options
    ): void {
        $builder
            ->add("name", TextType::class, [
                "label" => "championship.name",
                "required" => true,
                "attr" => ["autocomplete" => "off"],
            ])
            ->add("date_start", DateType::class, [
                "label" => "championship.date_start",
                "widget" => "single_text",
                "format" => "dd/MM/yyyy",
                "html5" => false,
                "attr" => [
                    "class" => "input date datepicker-input",
                    "autocomplete" => "off",
                ],
            ])
            ->add("date_end", DateType::class, [
                "label" => "championship.date_end",
                "widget" => "single_text",
                "format" => "dd/MM/yyyy",
                "html5" => false,
                "attr" => [
                    "class" => "input date datepicker-input",
                    "autocomplete" => "off",
                ],
            ])
            ->add("public", CheckboxType::class, [
                "label" => "Championnat public ?",
                "required" => false,
                "attr" => ["autocomplete" => "off"],
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            "data_class" => Championship::class,
        ]);
    }
}

src/Controller/ChampionshipController.php
<?php

namespace App\Controller;

use App\Entity\Championship;
use App\Entity\Player;
use App\Form\ChampionshipType;
use App\Repository\ChampionshipRepository;
use App\Repository\PlayerRepository;
use App\Repository\TournamentRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[
    Route([
        "fr" => "/championnats",
        "en" => "/championships",
    ])
]
class ChampionshipController extends BaseController
{
    #[Route("/", name: "app_championship_index", methods: ["GET"])]
    public function index(
        ChampionshipRepository $championshipRepository
    ): Response {
        return $this->render("championship/index.html.twig", [
            "championships" => array_filter(
                $championshipRepository->findAll(),
                fn(Championship $championship) => $this->isGranted(
                    "VIEW_CHAMPIONSHIP_TOURNAMENT",
                    $championship
                )
            ),
        ]);
    }

    #[
        Route(
            [
                "fr" => "/nouveau",
                "en" => "/new",
            ],
            name: "app_championship_new",
            methods: ["GET", "POST"]
        )
    ]
    public function new(
        Request $request,
        EntityManagerInterface $entityManager
    ): Response {
        if (!$this->isGranted("CREATE_CHAMPIONSHIP_TOURNAMENT")) {
            $this->addFlash(
                "error",
                "Vous n'avez pas les droits pour effectuer cette action"
            );
            return $this->redirectToRoute("app_championship_index");
        }
        $championship = new Championship();
        $form = $this->createForm(ChampionshipType::class, $championship);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($championship);
            $entityManager->flush();

            return $this->redirectToRoute(
                "app_championship_index",
                [],
                Response::HTTP_SEE_OTHER
            );
        }

        return $this->render("championship/new.html.twig", [
            "championship" => $championship,
            "form" => $form,
        ]);
    }

    #[Route("/{id}", name: "app_championship_show", methods: ["GET"])]
    public function show(
        Championship $championship,
        PlayerRepository $playerRepository,
        TournamentRepository $tournamentRepository
    ): Response {
        $allChampionshipPlayers = $playerRepository->getAllPlayerByChampionShip(
            $championship
        );
        $allTournaments = $tournamentRepository->findBy([
            "championship" => $championship,
        ]);
        usort(
            $allChampionshipPlayers,
            fn(
                Player $playerA,
                Player $playerB
            ) => $playerB->getTotalPointsByChampionship($championship) <=>
                $playerA->getTotalPointsByChampionship($championship)
        );
        return $this->render("championship/show.html.twig", [
            "championship" => $championship,
            "allChampionshipPlayers" => $allChampionshipPlayers,
            "allTournaments" => $allTournaments,
        ]);
    }

    #[
        Route(
            [
                "fr" => "/{id}/modifier",
                "en" => "/{id}/edit",
            ],
            name: "app_championship_edit",
            methods: ["GET", "POST"]
        )
    ]
    public function edit(
        Request $request,
        Championship $championship,
        EntityManagerInterface $entityManager
    ): Response {
        if (!$this->isGranted("EDIT_CHAMPIONSHIP_TOURNAMENT", $championship)) {
            $this->addFlash(
                "error",
                "Vous n'avez pas les droits pour effectuer cette action"
            );
            return $this->redirectToRoute("app_tournament_index");
        }
        $form = $this->createForm(ChampionshipType::class, $championship);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute(
                "app_championship_index",
                [],
                Response::HTTP_SEE_OTHER
            );
        }

        return $this->render("championship/edit.html.twig", [
            "championship" => $championship,
            "form" => $form->createView(),
        ]);
    }

    #[
        Route(
            "/delete/{id}",
            name: "app_championship_delete",
            methods: ["DELETE"]
        )
    ]
    public function delete(
        Request $request,
        Championship $championship,
        EntityManagerInterface $entityManager
    ): Response {
        if (
            !$this->isGranted("DELETE_CHAMPIONSHIP_TOURNAMENT", $championship)
        ) {
            $this->addFlash(
                "error",
                "Vous n'avez pas les droits pour effectuer cette action"
            );
            return $this->redirectToRoute("app_tournament_index");
        }
        $entityManager->remove($championship);
        $entityManager->flush();
        return new JsonResponse("", Response::HTTP_OK, [
            "HX-Redirect" => $this->generateUrl("app_championship_index"),
        ]);
    }
}

templates/championship/_delete_form.html.twig
{% if id is defined %}
    {% set idToDelete = id %}
{% else %}
    {% set idToDelete = form.vars.data.id %}
{% endif %}
<a class="btn btn-danger" hx-headers='{"X-CSRFToken": "{{ csrf_token('delete'~idToDelete) }}"}' )
   hx-delete="{{ path('app_championship_delete', {id: idToDelete}) }}"
   hx-confirm="Voulez-vous supprimer ce championnat ?">{{ "btn.delete"|trans }}</a>

templates/championship/_form.html.twig
{{ form_start(form, {'attr': {'id': 'championship'}}) }}
    {{ form_widget(form) }}
{{ form_end(form) }}
<div class="btn-group">
    <button form="{{ form.vars.id }}"
            class="btn btn-primary">{% if form.vars.data.id %}{{ "btn.edit"|trans }}{% else %}{{ "btn.create"|trans }}{% endif %}</button>
    {% if form.vars.data.id %}
        {% include 'championship/_delete_form.html.twig' with {"form":form} %}
    {% endif %}
    <a class="btn btn-warning" href="{{ path('app_championship_index') }}">{{ "btn.back"|trans }}</a>
</div>

templates/championship/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier un championat{% endblock %}

{% block body %}
    <section class="bg-body-secondary col-md-6 p-3">
        <h1>Modifier un championnat</h1>
        <div>
            {{ include('championship/_form.html.twig') }}
        </div>
    </section>
{% endblock %}

templates/championship/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Les championats{% endblock %}

{% block body %}
    <div class="align-self-start container-fluid ">
        <h1>{{ "championship.list"|trans }}</h1>
        <table class="table table-striped text-center">
            <thead>
            <tr>
                <th>{{ "championship.name"|trans }}</th>
                <th>{{ "championship.date_start"|trans }}</th>
                <th>{{ "championship.date_end"|trans }}</th>
                <th>{{ "championship.actions"|trans }}</th>
            </tr>
            </thead>
            <tbody>
            {% for championship in championships %}
                <tr>
                    <td>{{ championship.name }}</td>
                    <td>{{ championship.dateStart ? championship.dateStart|date('d/m/Y') : '' }}</td>
                    <td>{{ championship.dateEnd ? championship.dateEnd|date('d/m/y') : '' }}</td>
                    <td>
                        <div class="btn-group btn-group-sm d-flex align-items-center justify-content-center">
                            <a class="btn btn-primary"
                               href="{{ path('app_championship_show', {'id': championship.id}) }}">{{ "btn.show"|trans }}</a>
                            {% if is_granted("EDIT_CHAMPIONSHIP_TOURNAMENT",championship)%}
                            <a class="btn btn-secondary"
                               href="{{ path('app_championship_edit', {'id': championship.id}) }}">{{ "btn.edit"|trans }}</a>
                            {% endif %}
                        </div>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="4">{{ "championship.none"|trans }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        {% if is_granted("CREATE_CHAMPIONSHIP_TOURNAMENT") %}
        <a class="btn btn-success" href="{{ path('app_championship_new') }}">{{ "btn.create"|trans }}</a>
        {% endif %}
    </div>
{% endblock %}

templates/championship/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Créer un championat{% endblock %}

{% block body %}
    <section class="bg-body-secondary col-md-6 p-3">
        <h1>Créer un championat</h1>
        <div>
            {{ include('championship/_form.html.twig') }}
        </div>
    </section>
{% endblock %}

templates/championship/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Championat - {{ championship.name }}{% endblock %}

{% block body %}
    <div class="container-fluid" style="align-self: start">
        <h1>{{ championship.name }} - {{ championship.getPercentDone() }}%</h1>
        <div class="progress my-1">
            <div class="progress-bar" style="width: {{ championship.getPercentDone() }}%" role="progressbar"
                 aria-label="Pourcentage d'avancement du championat" aria-valuenow="{{ championship.getPercentDone }}"
                 aria-valuemin="0" aria-valuemax="100"></div>
        </div>
        <table class="table table-striped table-bordered">
            <tbody>
            <tr>
                <th>{{ "championship.name"|trans }}</th>
                <td>{{ championship.name }}</td>
            </tr>
            <tr>
                <th>{{ "championship.date_start"|trans }}</th>
                <td>{{ championship.dateStart ? championship.dateStart|date('d/m/y') : '' }}</td>
            </tr>
            <tr>
                <th>{{ "championship.date_start"|trans }}</th>
                <td>{{ championship.dateEnd ? championship.dateEnd|date('d/m/y') : '' }}</td>
            </tr>
            </tbody>
        </table>
        <div class="accordion">
            <details class="accordion-item border-bottom-0 mb-2">
                <summary class="accordion-button"><p class="accordion-header user-select-none">Total des points</p>
                </summary>
                <table class="table-striped table-hover table table-bordered accordion-body border-bottom px-2 text-center">
                    <tbody>
                    <tr>
                        <td>JOUEUR</td>
                        <td>POINTS</td>
                    </tr>
                    {% for player in allChampionshipPlayers %}
                        <tr>
                            <td>{{ player.name }}</td>
                            <td>{{ player.getTotalPointsByChampionship(championship) }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </details>
            <div class="accordion">
                <details class="accordion-item border-bottom-0">
                    <summary class="accordion-button"><p class="accordion-header user-select-none">Scores par tournois</p></summary>
                    <div class="accordion-body border-bottom px-2">
                        {% for tournament in allTournaments %}
                            <div class="accordion">
                                {% include "tournament/_partial/details.html.twig" with {"tournament":tournament} %}
                            </div>
                        {% endfor %}
                    </div>
                </details>

            </div>
        </div>
        <div class="btn-group mt-2">
            {% if is_granted("ROLE_ADMIN") and adminCreatedChampionship(app.user,championship) %}
            <a class="btn btn-primary"
               href="{{ path('app_championship_edit', {'id': championship.id}) }}">{{ "btn.edit"|trans }}</a>
            {% endif %}
            <a class="btn btn-warning" href="{{ path('app_championship_index') }}">{{ "btn.back"|trans }}</a>
        </div>
    </div>
{% endblock %}